Terraforming Upgrades
SolCorporation/ColonyStation-Legacy pull request #24
Opened 2019-12-02 18:58 UTC by TheGamerdk

### Intent of your Pull Request
Adds upgrades & an upgrade container for the Terraformer
Contains 3 upgrades for now

Phasic Gas Manipulation
Reduces power usage by 25%

Plasma Quantum Beaming
Allows plasma terraforming

Electromagnetic Infusion
Adds 0.1 moles per tick.

Small PR, school busy

#### Changelog

:cl:  
rscadd: There are now upgrade boards for the terraformer
bugfix: Fixes a few sneaky reactor + generator bugs
/:cl:

2019-12-02 21:28 UTC, Ktlwjec requested changes

2019-12-02 21:28 UTC, Ktlwjec commented on code/modules/terraforming/upgrades.dm
> +	desc = "An accessory to the terraformer, that accepts various upgrades"
A dot please: desc = "An accessory to the terraformer, that accepts various upgrades."

2019-12-02 21:28 UTC, Ktlwjec commented on code/modules/terraforming/upgrades.dm
> +	desc = "Allows the terraformer to produce plasma, a very flammable and very potent greenhouse gas"
A dot please:  desc = "Allows the terraformer to produce plasma, a very flammable and very potent greenhouse gas."

2019-12-02 21:28 UTC, Ktlwjec commented on code/modules/terraforming/upgrades.dm
> +	desc = "The terraformer now produces an additional 0.1 moles of gas"
A dot please: desc = "The terraformer now produces an additional 0.1 moles of gas."

2020-01-01 20:35 UTC, closed without merging

2020-02-06 19:25 UTC, TheGamerdk commented
This got merged later